apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd  # Falls du ArgoCD in einem eigenen Namespace installiert hast
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/patrickdaumann/argocdmyapp.git
    targetRevision: main
    path: dev/myapp  # Das Verzeichnis im Repository, in dem deine Manifeste liegen
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true